#include <gtest/gtest.h>

#include "./thread/ThreadUnitTest.hpp"
#include "./thread/ThreadConditionUnitTest.hpp"
#include "./ping/PingTest.hpp"
#include "./graph/GraphEdgeUnitTest.hpp"
#include "./graph/actions/ActionFactoryUnitTest.hpp"
#include "./graph/actions/ScriptActionUnitTest.hpp"
#include "./graph/nodes/AnimateScriptNodeUnitTest.hpp"
#include "./graph/nodes/ScriptNodeUnitTest.hpp"
#include "./graph/nodes/TriggerNodeUnitTest.hpp"
#include "./persist/HiveBuilderUnitTest.hpp"
#include "./persist/json/JsonHiveLoaderUnitTest.hpp"
#include "./persist/json/JsonHarnessLoaderUnitTest.hpp"
#include "./graph/actions/AgentVisibleAnimateUnitTest.hpp"
#include "./scene/SceneTest.hpp"
